# Generated by Django 3.0.8 on 2020-07-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoreapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeorderID', models.CharField(max_length=100)),
                ('custNum', models.IntegerField()),
                ('bookID', models.IntegerField()),
            ],
        ),
    ]
